### ISSUE TITLE
Agent not starting

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#202]
Multiple users are reporting not being able to start their agents.

**Comment by oaksprout** [comment]
Potentially solved by: https://github.com/valory-xyz/olas-operate-app/pull/216

**Comment by oaksprout** [comment]
These are potentially resolved by giving the user better guidance when they're evicted.

**Comment by oaksprout** [comment]
User logs: 
[pearl_logs_2024-07-12T17_12_40.961Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16231505/pearl_logs_2024-07-12T17_12_40.961Z-0.1.0-rc71.zip)

**Comment by oaksprout** [comment]
Another user's logs 
[pearl_logs_2024-07-12T16_57_01.762Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16231514/pearl_logs_2024-07-12T16_57_01.762Z-0.1.0-rc71.zip)

**Comment by oaksprout** [comment]
Third user's logs: 
[P1LE70~H.ZIP](https://github.com/user-attachments/files/16231529/P1LE70.H.ZIP)

**Comment by oaksprout** [comment]
Another afflicted user: 
[pearl_logs_2024-07-18T12_16_32.726Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16283083/pearl_logs_2024-07-18T12_16_32.726Z-0.1.0-rc71.zip)

**Comment by oaksprout** [comment]
@jmoreira-valory I brought an old agent back to life and have experienced the same symptoms as described above. Agent loads forever. 

My naive read is that it looks like a gas estimation issue.

[pearl_logs_2024-07-22T16:51:32.968Z-0.1.0-rc80.zip](https://github.com/user-attachments/files/16337195/pearl_logs_2024-07-22T16.51.32.968Z-0.1.0-rc80.zip)

**Comment by oaksprout** [comment]
Another agent with the same issue I described above – old agent @jmoreira-valory.

Let me know if it's a different case – can create a separate issue.

[pearl_logs_2024-07-22T17_08_21.998Z-0.1.0-rc71.zip](https://github.com/user-attachments/files/16337552/pearl_logs_2024-07-22T17_08_21.998Z-0.1.0-rc71.zip)

**Comment by jmoreira-valory** [comment]
Last 2 cases (services 466 and 471) seem unrelated to the main issue in this ticket. Apparently the RPC is being inconsistent in the executions shown in the log files.
