### ISSUE TITLE
Excessively large agent logs

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#207]
Agent log files can grow to be multiple GB. This is inconvenient for users, and inconvenient for sharing logs.

Agent logs are located in `.operate/services/<bafybei...>/deployment/agent/log.txt`.

**Comment by truemiller** [comment]
@oaksprout these logs need to be rotated/pruned by either the agent or middleware (whichever is writing them)

some agent associated logs are coming through with the cli logs that are being captured currently, these will be rotated and pruned at 10mb once https://github.com/valory-xyz/olas-operate-app/pull/218 is merged.

**Comment by oaksprout** [comment]
Just to clarify, @joshmlxn, #218 doesn't resolve the large log.txt file and that requires some backend work?

**Comment by truemiller** [comment]
> Just to clarify, @joshmlxn, #218 doesn't resolve the large log.txt file and that requires some backend work?

yes, either the middleware or the agent is writing these logs. it would be fine if the log.txt file write was turned off, and they just "proxied" through the cli by printing as required, then the logs would be rotated/pruned as they are in the implementation for #218

**Comment by oaksprout** [comment]
This appears to have been resolved on the agent. Two of my up to date agents have .operate folder sizes of approx 160MB, where previously they would've been several GB.
