### ISSUE TITLE
Multiplication of Tendermint processes

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#214]
Version: rc61 + rc60

Multiple users have reported that when they leave the app on for extended periods of time, it continuously spawns tendermint processes. This ends up taking up a significant and problematic amount of CPU resources.

![image](https://github.com/valory-xyz/olas-operate-app/assets/66292936/4d4fbe7d-ffa7-4693-9f79-2d0e47e995b3)

**Comment by dagacha** [comment]
When opening Pearl after the app being not running and subsequently starting the agent this is what I see
![image](https://github.com/valory-xyz/olas-operate-app/assets/35235550/e93abe94-7dad-43cd-bc76-bed598847886)

If leave Pearl running, close the lid of the laptop, and re-open it after a few mins, nothing changes. I've repeated the process 3 times.

If I pause the agent using Pearl's UI, and re-start it, a new tendermint process appears:
<img width="935" alt="image" src="https://github.com/valory-xyz/olas-operate-app/assets/35235550/41c03b4d-35a2-4893-b1ae-76bbd3552c2b">

If I repeat the latter, new tendermint processes appear
<img width="840" alt="image" src="https://github.com/valory-xyz/olas-operate-app/assets/35235550/38b6d4a5-e89a-4262-bdd9-5bc329270e0c">

cc @jmoreira-valory

**Comment by dagacha** [comment]
On top of that, closing Pearl does not kill the process `aea_bin`

Closing subsequently killing the process `aea_bin` doesn't kill the tendermint processes.

Finally I can stop the tendermint processes by killing them directly.

**Comment by oaksprout** [comment]
I've also noted that when I close the app, several tendermint processes remain running.

<img width="743" alt="image" src="https://github.com/valory-xyz/olas-operate-app/assets/66292936/e26c5f5c-d92d-41c6-9702-ff9db934ff66">

Same for aea_bin

<img width="736" alt="image" src="https://github.com/valory-xyz/olas-operate-app/assets/66292936/891138f5-5c21-4210-812f-6999ead480b4">

**Comment by dagacha** [comment]
Different behavoiur observed: Pearl running in the background, laptop lid closed for 5-6hs, when opening laptop back lots of tendermint processes running. This time I did not pause / restart agent.

<img width="850" alt="image" src="https://github.com/valory-xyz/olas-operate-app/assets/35235550/7ceee3a1-ee13-4f1e-ad66-fea7f9e48346">

**Comment by oaksprout** [comment]
@solarw can you reference your branch with the fix here?

**Comment by oaksprout** [comment]
Potentially solved by: https://github.com/valory-xyz/olas-operate-app/pull/216

**Comment by oaksprout** [comment]
I also tested leaving the app and agent running whilst I put my Mac to sleep – closed the lid.

When I re-opened the computer, the processes remain consistent.
