### ISSUE TITLE
Key file duplication

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#219]
One user has reported that they:

- created an account
- closed the app
- reopened the app
- was taken back to the create account screen

The user has reported 12 key files in .operate/keys.

An additional user has subsequently reported this.

App logs from an affected user: 
[logs (15).txt](https://github.com/user-attachments/files/16141943/logs.15.txt) The user appears to have been on quite an old version of the app – logs don't reveal the exact version, but it was likely pre rc60.

**Comment by oaksprout** [comment]
Before leaving, Viraj said he suspected there's an issue with inadequate handling of RPC failures during the account creation step. Feels like a good line of investigation.

**Comment by oaksprout** [comment]
@jmoreira-valory can you reference the related PR and close?

**Comment by jmoreira-valory** [comment]
Addressed in #228
