### ISSUE TITLE
Agent start button greyed out after migrating to new contracts. RC117

### ISSUE THREAD

**Issue by adrianoVal** [valory-xyz/olas-operate-app#291]
<img width="608" alt="Screenshot 2024-08-23 at 18 45 33" src="https://github.com/user-attachments/assets/524170f0-a39b-463e-8749-b4edcd0b99da">

[pearl_logs_2024-08-22T20_30_48.890Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16731610/pearl_logs_2024-08-22T20_30_48.890Z-0.1.0-rc117.zip)

**Comment by adrianoVal** [comment]
Another user seems to be having the same issue: 
[pearl_logs_2024-08-23T23_29_23.862Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16748981/pearl_logs_2024-08-23T23_29_23.862Z-0.1.0-rc117.zip)

**Comment by truemiller** [comment]
> <img alt="Screenshot 2024-08-26 at 15 10 03" width="560" src="https://private-user-images.githubusercontent.com/90184519/361443109-e78830b2-2620-48cd-b4e3-a6333be000de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTE3NTcsIm5iZiI6MTcyNDc1MTQ1NywicGF0aCI6Ii85MDE4NDUxOS8zNjE0NDMxMDktZTc4ODMwYjItMjYyMC00OGNkLWI0ZTMtYTYzMzNiZTAwMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NzI3Y2VhMDg0MmUzZjk4ZTBmMTNkZmVmMTA5MmY5NDRhMDQ5MGMxOWFkYWM5MGI2ZTIzYmI0ZDUyZmY4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9kXXmGiXFCrsKYI4dFF_MhxqB31c7joWuwcPTmSUA4">
> Another user seems to be having the same issue: [pearl_logs_2024-08-23T23_29_23.862Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16748981/pearl_logs_2024-08-23T23_29_23.862Z-0.1.0-rc117.zip)

**electron.log**
backend is not running at this point, though CLI logs show responses around this time
```
2024-08-21T03:26:39.657Z electron: Setting up store IPC
2024-08-22T16:00:48.871Z electron: Creating required directories
2024-08-22T16:00:48.874Z electron: Checking tendermint installation
**2024-08-22T16:00:48.901Z electron: Backend not running!**
```

**debug_data.txt** 
backend is not running, hence no receipt of service data from the API
```
  "services": {
    "serviceStatus": "undefined",
    "services": []
  },
```

low memory, only 40Mb available?
```
Total Memory: 8589934592 // 8.5GB
Free Memory:  40747008   // 40MB
```
