### ISSUE TITLE
Pearl registers "balance too low" after adding the additional OLAS stake after contract migration

### ISSUE THREAD

**Issue by adrianoVal** [valory-xyz/olas-operate-app#292]
[pearl_logs_2024-08-26T12_41_14.898Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16749028/pearl_logs_2024-08-26T12_41_14.898Z-0.1.0-rc117.zip)

<img width="230" alt="Screenshot 2024-08-26 at 15 14 08" src="https://github.com/user-attachments/assets/3405d8ad-a4c6-4ad9-bc64-e806a742e0bd">

**Comment by adrianoVal** [comment]
Another user with a similar issue:

<img width="227" alt="Screenshot 2024-08-26 at 15 34 56" src="https://github.com/user-attachments/assets/689ecd93-364f-4647-97a2-2734412bef60">

 
[pearl_logs_2024-08-26T09_28_33.285Z-0.1.0-rc117.zip](https://github.com/user-attachments/files/16749234/pearl_logs_2024-08-26T09_28_33.285Z-0.1.0-rc117.zip)

**Comment by Etandooley** [comment]
@adrianoVal Are you having a problem with staking?

**Comment by truemiller** [comment]
Initial 20 OLAS was spent during registration, most recent 20 OLAS balance in safe was sent after this.
![image](https://github.com/user-attachments/assets/b342e29d-ed13-45e0-b8eb-4ffc0133b145)
