### ISSUE TITLE
Multi-contract Issues

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#318]
- [x] Cannot switch back to Pearl Beta

<img width="458" alt="image" src="https://github.com/user-attachments/assets/881dcf8d-3205-442d-865b-b95f7e6c5b1a">

- [x] shouldn't say "New"

<img width="271" alt="image" src="https://github.com/user-attachments/assets/48373001-0491-4fd4-9043-1be659f3c354">

**Comment by truemiller** [comment]
switching back to beta fixed in #343 migration refactor
new badge was removed in #338 

both are in rc127
