### ISSUE TITLE
Backup wallet is not added to master Safe

### ISSUE THREAD

**Issue by oaksprout** [valory-xyz/olas-operate-app#331]
User adds a backup wallet, but it isn't persisted.

[pearl_logs_2024-09-06T11-55-08.075Z-0.1.0-rc125.zip](https://github.com/user-attachments/files/16918076/pearl_logs_2024-09-06T11-55-08.075Z-0.1.0-rc125.zip)

Severity: critical. 2 users reported, fundamentally affects security.

**Comment by oaksprout** [comment]
@truemiller we don't know if they added the wallet on creation, they can't remember.

Note that I previously had an issue where a non-checksummed address was not possible to add – not sure if that's related. Would show up in the cli.log if so.

**Comment by oaksprout** [comment]
Logs from another affected user 
[pearl_logs_2024-09-08.zip](https://github.com/user-attachments/files/16928933/pearl_logs_2024-09-08.zip)

**Comment by truemiller** [comment]
Checksumming should solve this, but can reopen if this experienced again.
