### ISSUE TITLE
Taskbar icon does not reopen Pearl (Windows)

### ISSUE THREAD

**Issue by iasonrovis** [valory-xyz/olas-operate-app#344]
"When i close pearl (windows) and try to reopen it, it never reopens. I need to restart my computer for it to work again. It looks like it tries to open something - all the applications on the taskbar move to the left then they shift back to the original position."

[Discord ticket](https://discord.com/channels/899649805582737479/1283096310941224961) 

[Pearl logs 120924.zip](https://github.com/user-attachments/files/16983082/Pearl.logs.120924.zip)

**Comment by truemiller** [comment]
Need to enable taskbar icon double click.
User should be able to open if they right click the icon instead, and click Show app.
